#!/bin/bash
set -euo pipefail
# enable job control consistently, not just when there is a tty:
set -m
IFS=

intersection=target/release/intersection

tmp=$(mktemp)
tmp10=$(mktemp)
tmp11=$(mktemp)
tmp12=$(mktemp)
err=$(mktemp)
exitcode=$(mktemp)

test_intersection() {
    subtest="$1"
    shift

    echo "Testing intersection $@ in $subtest..."
    set -x
    $intersection --sorted "$@" test/intersection/"$subtest"/in/{a,b} > "$tmp"
    diff -u test/intersection/"$subtest"/out/a+b "$tmp"

    $intersection --sorted --fddrop "$@" test/intersection/"$subtest"/in/{a,b,c} > "$tmp" \
                  10> "$tmp10" 11> "$tmp11" 12> "$tmp12"
    diff -u test/intersection/"$subtest"/out/a+b+c "$tmp"
    diff -u test/intersection/"$subtest"/out/a+b+c.10 "$tmp10"
    diff -u test/intersection/"$subtest"/out/a+b+c.11 "$tmp11"
    diff -u test/intersection/"$subtest"/out/a+b+c.12 "$tmp12"

    $intersection --sorted "$@" test/intersection/"$subtest"/in/{b,c} > "$tmp"
    diff -u test/intersection/"$subtest"/out/b+c "$tmp"

    if $intersection --sorted "$@" test/intersection/"$subtest"/in/{b,c,unsorted} > "$tmp" 2> "$err"; then
        echo "error: expected intersection to error out here, it didn't"
        false
    fi
    diff -u test/intersection/"$subtest"/out/b+c+unsorted "$tmp"
    diff -u test/intersection/"$subtest"/out/b+c+unsorted.err "$err"

    (
        set +e
        $intersection --sorted "$@" test/intersection/"$subtest"/in/{b,c,d} > "$tmp" 2> "$err"
        echo $? > "$exitcode"
    )
    diff -u test/intersection/"$subtest"/out/b+c+d "$tmp"
    diff -u test/intersection/"$subtest"/out/b+c+d.err "$err"
    diff -u test/intersection/"$subtest"/out/b+c+d.exitcode "$exitcode"

    set +x
}

test_intersection 1_normal
test_intersection 2_numeric --numeric
