#!/bin/bash
set -meuo pipefail
IFS=

out=$(mktemp)
err=$(mktemp)

#set -x

cargo_target=${CARGO_TARGET-release}

target/"$cargo_target"/priorities-restore-mtimes

if target/"$cargo_target"/priorities test/priorities/ -t "2024/10/06 08:00:00" > "$out" 2> "$err"; then
    echo "expecting exit code 1, got 0"
    false
else
    e=$?
    if [ $e -ne 1 ]; then
        echo "expecting exit code 1, got $e"
        false
    fi
fi


errors=0

if ! diff -u test/priorities.out "$out"; then
    errors=$(( errors + 1 ))
fi

# Remove the lines with \t indentation, since those are backtraces
# that carry changing line numbers.
filtered_err=$(mktemp)
grep -E -v '^	' < "$err" > "$filtered_err"

if ! diff -u test/priorities.err "$filtered_err"; then
    errors=$(( errors + 1 ))
fi

if [ $errors -eq 0 ]; then
    rm -f "$out" "$err" "$filtered_err"
fi

exit $errors
