#!/bin/bash
set -euo pipefail
# enable job control consistently, not just when there is a tty:
set -m
IFS=

intersection=target/release/intersection

tmp=$(mktemp)
err=$(mktemp)

test_intersection() {
    subtest="$1"
    shift

    echo "Testing intersection $@ in $subtest..."
    set -x
    $intersection --sorted "$@" test/intersection/"$subtest"/in/{a,b} > "$tmp"
    diff -u test/intersection/"$subtest"/out/a+b "$tmp"

    $intersection --sorted "$@" test/intersection/"$subtest"/in/{a,b,c} > "$tmp"
    diff -u test/intersection/"$subtest"/out/a+b+c "$tmp"

    $intersection --sorted "$@" test/intersection/"$subtest"/in/{b,c} > "$tmp"
    diff -u test/intersection/"$subtest"/out/b+c "$tmp"

    if $intersection --sorted "$@" test/intersection/"$subtest"/in/{b,c,unsorted} > "$tmp" 2> "$err"; then
        echo "error: expected intersection to error out here, it didn't"
        false
    fi
    diff -u test/intersection/"$subtest"/out/b+c+unsorted "$tmp"
    diff -u test/intersection/"$subtest"/out/b+c+unsorted.err "$err"

    set +x
}

test_intersection 1_normal
test_intersection 2_numeric --numeric
