#!/bin/bash
set -meuo pipefail
IFS=

check_clean() {
    local s
    s=$(git status --porcelain)
    if  [ -n "$s" ]; then
        echo "git status is not clean:"
        echo "$s"
        false
    fi
}

check_clean

test/priorities-store-mtimes

check_clean

make test

echo "Ready for release."
